;;; Below is an example font file generated by the Python tile generator, provided so you don't have
;;; to install Python or its png module if you don't want to.
;;;
;;; Use it by changing this line in the Makefile:
;;;
;;;     FONT_FILE := $(DATA_DIR)/font.png
;;; 
;;; to the path of this file:
;;; 
;;;     FONT_FILE := $(DATA_DIR)/font.s
	
;;; ============================================================================
;;; This is a code tile font file generated by tile_generator.py from:
;;;     data/font.png
;;;
;;; It is intended for usage with video mode 96.

#include "../common.def.h"

	.section .text
	.global m96_font

m96_font:
	;; TILE 0
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 1
	.byte	4	; 000100
	.byte	11	; 001110
	.byte	11	; 001110
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	0	; 000000
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 2
	.byte	24	; 011011
	.byte	24	; 011011
	.byte	15	; 010010
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 3
	.byte	0	; 000000
	.byte	8	; 001010
	.byte	27	; 011111
	.byte	8	; 001010
	.byte	8	; 001010
	.byte	27	; 011111
	.byte	8	; 001010
	.byte	0	; 000000

	;; TILE 4
	.byte	6	; 001000
	.byte	11	; 001110
	.byte	13	; 010000
	.byte	9	; 001100
	.byte	2	; 000010
	.byte	25	; 011100
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 5
	.byte	22	; 011001
	.byte	22	; 011001
	.byte	2	; 000010
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	16	; 010011
	.byte	16	; 010011
	.byte	0	; 000000

	;; TILE 6
	.byte	6	; 001000
	.byte	17	; 010100
	.byte	17	; 010100
	.byte	6	; 001000
	.byte	18	; 010101
	.byte	15	; 010010
	.byte	10	; 001101
	.byte	0	; 000000

	;; TILE 7
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	6	; 001000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 8
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 9
	.byte	6	; 001000
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	0	; 000000

	;; TILE 10
	.byte	0	; 000000
	.byte	8	; 001010
	.byte	11	; 001110
	.byte	27	; 011111
	.byte	11	; 001110
	.byte	8	; 001010
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 11
	.byte	0	; 000000
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	27	; 011111
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 12
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	6	; 001000

	;; TILE 13
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	27	; 011111
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 14
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	0	; 000000

	;; TILE 15
	.byte	0	; 000000
	.byte	1	; 000001
	.byte	2	; 000010
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	13	; 010000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 16
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	16	; 010011
	.byte	18	; 010101
	.byte	22	; 011001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 17
	.byte	4	; 000100
	.byte	9	; 001100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 18
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	1	; 000001
	.byte	5	; 000110
	.byte	6	; 001000
	.byte	13	; 010000
	.byte	27	; 011111
	.byte	0	; 000000

	;; TILE 19
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	1	; 000001
	.byte	11	; 001110
	.byte	1	; 000001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 20
	.byte	2	; 000010
	.byte	5	; 000110
	.byte	8	; 001010
	.byte	15	; 010010
	.byte	27	; 011111
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	0	; 000000

	;; TILE 21
	.byte	27	; 011111
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	1	; 000001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 22
	.byte	5	; 000110
	.byte	6	; 001000
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 23
	.byte	27	; 011111
	.byte	1	; 000001
	.byte	2	; 000010
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	0	; 000000

	;; TILE 24
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 25
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	12	; 001111
	.byte	1	; 000001
	.byte	2	; 000010
	.byte	9	; 001100
	.byte	0	; 000000

	;; TILE 26
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	0	; 000000
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	0	; 000000

	;; TILE 27
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	0	; 000000
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	6	; 001000

	;; TILE 28
	.byte	2	; 000010
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	13	; 010000
	.byte	6	; 001000
	.byte	4	; 000100
	.byte	2	; 000010
	.byte	0	; 000000

	;; TILE 29
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	27	; 011111
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	27	; 011111
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 30
	.byte	6	; 001000
	.byte	4	; 000100
	.byte	2	; 000010
	.byte	1	; 000001
	.byte	2	; 000010
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	0	; 000000

	;; TILE 31
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	1	; 000001
	.byte	5	; 000110
	.byte	4	; 000100
	.byte	0	; 000000
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 32
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	20	; 010111
	.byte	18	; 010101
	.byte	20	; 010111
	.byte	13	; 010000
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 33
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	27	; 011111
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 34
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	0	; 000000

	;; TILE 35
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 36
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	0	; 000000

	;; TILE 37
	.byte	27	; 011111
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	27	; 011111
	.byte	0	; 000000

	;; TILE 38
	.byte	27	; 011111
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	0	; 000000

	;; TILE 39
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	13	; 010000
	.byte	20	; 010111
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	12	; 001111
	.byte	0	; 000000

	;; TILE 40
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	27	; 011111
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 41
	.byte	11	; 001110
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 42
	.byte	1	; 000001
	.byte	1	; 000001
	.byte	1	; 000001
	.byte	1	; 000001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 43
	.byte	14	; 010001
	.byte	15	; 010010
	.byte	17	; 010100
	.byte	21	; 011000
	.byte	17	; 010100
	.byte	15	; 010010
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 44
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	27	; 011111
	.byte	0	; 000000

	;; TILE 45
	.byte	14	; 010001
	.byte	24	; 011011
	.byte	18	; 010101
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 46
	.byte	14	; 010001
	.byte	22	; 011001
	.byte	18	; 010101
	.byte	16	; 010011
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 47
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 48
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	0	; 000000

	;; TILE 49
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	18	; 010101
	.byte	15	; 010010
	.byte	10	; 001101
	.byte	0	; 000000

	;; TILE 50
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	15	; 010010
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 51
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	13	; 010000
	.byte	11	; 001110
	.byte	1	; 000001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 52
	.byte	27	; 011111
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 53
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 54
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	8	; 001010
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 55
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	18	; 010101
	.byte	18	; 010101
	.byte	18	; 010101
	.byte	18	; 010101
	.byte	8	; 001010
	.byte	0	; 000000

	;; TILE 56
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	8	; 001010
	.byte	4	; 000100
	.byte	8	; 001010
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 57
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	8	; 001010
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 58
	.byte	26	; 011110
	.byte	2	; 000010
	.byte	4	; 000100
	.byte	6	; 001000
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	0	; 000000

	;; TILE 59
	.byte	11	; 001110
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 60
	.byte	0	; 000000
	.byte	13	; 010000
	.byte	6	; 001000
	.byte	4	; 000100
	.byte	2	; 000010
	.byte	1	; 000001
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 61
	.byte	11	; 001110
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 62
	.byte	4	; 000100
	.byte	8	; 001010
	.byte	14	; 010001
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 63
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	28	; 111111

	;; TILE 64
	.byte	9	; 001100
	.byte	9	; 001100
	.byte	4	; 000100
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 65
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	11	; 001110
	.byte	1	; 000001
	.byte	12	; 001111
	.byte	14	; 010001
	.byte	12	; 001111
	.byte	0	; 000000

	;; TILE 66
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	0	; 000000

	;; TILE 67
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	13	; 010000
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 68
	.byte	1	; 000001
	.byte	1	; 000001
	.byte	12	; 001111
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	12	; 001111
	.byte	0	; 000000

	;; TILE 69
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	13	; 010000
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 70
	.byte	5	; 000110
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	26	; 011110
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	0	; 000000

	;; TILE 71
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	12	; 001111
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	12	; 001111
	.byte	1	; 000001
	.byte	11	; 001110

	;; TILE 72
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	25	; 011100
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	0	; 000000

	;; TILE 73
	.byte	4	; 000100
	.byte	0	; 000000
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	5	; 000110
	.byte	0	; 000000

	;; TILE 74
	.byte	2	; 000010
	.byte	0	; 000000
	.byte	5	; 000110
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	15	; 010010
	.byte	9	; 001100

	;; TILE 75
	.byte	13	; 010000
	.byte	13	; 010000
	.byte	15	; 010010
	.byte	17	; 010100
	.byte	21	; 011000
	.byte	17	; 010100
	.byte	15	; 010010
	.byte	0	; 000000

	;; TILE 76
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	5	; 000110
	.byte	0	; 000000

	;; TILE 77
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	23	; 011010
	.byte	18	; 010101
	.byte	18	; 010101
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	0	; 000000

	;; TILE 78
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	25	; 011100
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	0	; 000000

	;; TILE 79
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	11	; 001110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 80
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	26	; 011110
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	26	; 011110
	.byte	13	; 010000

	;; TILE 81
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	12	; 001111
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	12	; 001111
	.byte	1	; 000001

	;; TILE 82
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	19	; 010110
	.byte	7	; 001001
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	25	; 011100
	.byte	0	; 000000

	;; TILE 83
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	11	; 001110
	.byte	13	; 010000
	.byte	11	; 001110
	.byte	1	; 000001
	.byte	11	; 001110
	.byte	0	; 000000

	;; TILE 84
	.byte	0	; 000000
	.byte	6	; 001000
	.byte	26	; 011110
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	8	; 001010
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 85
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	19	; 010110
	.byte	8	; 001010
	.byte	0	; 000000

	;; TILE 86
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	8	; 001010
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 87
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	18	; 010101
	.byte	27	; 011111
	.byte	8	; 001010
	.byte	0	; 000000

	;; TILE 88
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	9	; 001100
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	0	; 000000

	;; TILE 89
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	15	; 010010
	.byte	11	; 001110
	.byte	4	; 000100
	.byte	21	; 011000

	;; TILE 90
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	26	; 011110
	.byte	2	; 000010
	.byte	9	; 001100
	.byte	13	; 010000
	.byte	26	; 011110
	.byte	0	; 000000

	;; TILE 91
	.byte	5	; 000110
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	21	; 011000
	.byte	6	; 001000
	.byte	6	; 001000
	.byte	5	; 000110
	.byte	0	; 000000

	;; TILE 92
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	0	; 000000
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	4	; 000100
	.byte	0	; 000000

	;; TILE 93
	.byte	9	; 001100
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	3	; 000011
	.byte	2	; 000010
	.byte	2	; 000010
	.byte	9	; 001100
	.byte	0	; 000000

	;; TILE 94
	.byte	8	; 001010
	.byte	17	; 010100
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000
	.byte	0	; 000000

	;; TILE 95
	.byte	4	; 000100
	.byte	11	; 001110
	.byte	24	; 011011
	.byte	14	; 010001
	.byte	14	; 010001
	.byte	27	; 011111
	.byte	0	; 000000
	.byte	0	; 000000

	.section .text
	.global m96_rows
m96_rows:
	TILE_ROW	0	R_BG R_BG R_BG R_BG R_BG R_BG	; 000000
	TILE_ROW	1	R_BG R_BG R_BG R_BG R_BG R_FG	; 000001
	TILE_ROW	2	R_BG R_BG R_BG R_BG R_FG R_BG	; 000010
	TILE_ROW	3	R_BG R_BG R_BG R_BG R_FG R_FG	; 000011
	TILE_ROW	4	R_BG R_BG R_BG R_FG R_BG R_BG	; 000100
	TILE_ROW	5	R_BG R_BG R_BG R_FG R_FG R_BG	; 000110
	TILE_ROW	6	R_BG R_BG R_FG R_BG R_BG R_BG	; 001000
	TILE_ROW	7	R_BG R_BG R_FG R_BG R_BG R_FG	; 001001
	TILE_ROW	8	R_BG R_BG R_FG R_BG R_FG R_BG	; 001010
	TILE_ROW	9	R_BG R_BG R_FG R_FG R_BG R_BG	; 001100
	TILE_ROW	10	R_BG R_BG R_FG R_FG R_BG R_FG	; 001101
	TILE_ROW	11	R_BG R_BG R_FG R_FG R_FG R_BG	; 001110
	TILE_ROW	12	R_BG R_BG R_FG R_FG R_FG R_FG	; 001111
	TILE_ROW	13	R_BG R_FG R_BG R_BG R_BG R_BG	; 010000
	TILE_ROW	14	R_BG R_FG R_BG R_BG R_BG R_FG	; 010001
	TILE_ROW	15	R_BG R_FG R_BG R_BG R_FG R_BG	; 010010
	TILE_ROW	16	R_BG R_FG R_BG R_BG R_FG R_FG	; 010011
	TILE_ROW	17	R_BG R_FG R_BG R_FG R_BG R_BG	; 010100
	TILE_ROW	18	R_BG R_FG R_BG R_FG R_BG R_FG	; 010101
	TILE_ROW	19	R_BG R_FG R_BG R_FG R_FG R_BG	; 010110
	TILE_ROW	20	R_BG R_FG R_BG R_FG R_FG R_FG	; 010111
	TILE_ROW	21	R_BG R_FG R_FG R_BG R_BG R_BG	; 011000
	TILE_ROW	22	R_BG R_FG R_FG R_BG R_BG R_FG	; 011001
	TILE_ROW	23	R_BG R_FG R_FG R_BG R_FG R_BG	; 011010
	TILE_ROW	24	R_BG R_FG R_FG R_BG R_FG R_FG	; 011011
	TILE_ROW	25	R_BG R_FG R_FG R_FG R_BG R_BG	; 011100
	TILE_ROW	26	R_BG R_FG R_FG R_FG R_FG R_BG	; 011110
	TILE_ROW	27	R_BG R_FG R_FG R_FG R_FG R_FG	; 011111
	TILE_ROW	28	R_FG R_FG R_FG R_FG R_FG R_FG	; 111111
